// <auto-generated />
using System;
using ApiStarPare.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiStarPare.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250217144156_CreateStarPare")]
    partial class CreateStarPare
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ApiStarPare.Models.Carro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TotalPassageiros")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Carros");
                });

            modelBuilder.Entity("ApiStarPare.Models.Estacionamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CarroId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataEntrada")
                        .HasMaxLength(30)
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataSaida")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CarroId");

                    b.ToTable("Estacionamentos");
                });

            modelBuilder.Entity("ApiStarPare.Models.Estacionamento", b =>
                {
                    b.HasOne("ApiStarPare.Models.Carro", "CarroEstacionado")
                        .WithMany()
                        .HasForeignKey("CarroId");

                    b.Navigation("CarroEstacionado");
                });
#pragma warning restore 612, 618
        }
    }
}
